// ============================================================
//  MUNDIAL 2026 ANALYTICS — DATA LAYER (REAL — sorteo oficial 5 dic 2025)
//  48 equipos, 12 grupos (A–L). Fuente: FIFA / The Odds API.
//  Horarios en UTC (campo "utc"); la UI los convierte a la zona local.
//  Banderas: campo iso2 (flagcdn.com) — el emoji "flag" es solo fallback.
// ============================================================

const TEAMS = [
  { id:1, name:"México", shortName:"MEX", flag:"🇲🇽", iso2:"mx", group:"A", confederation:"CONCACAF", fifaRanking:15, color:"#006847", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.1, goalsConceded:0.9, starPlayerValue:81, starPlayer:"S. Giménez" },
  { id:2, name:"Sudáfrica", shortName:"RSA", flag:"🇿🇦", iso2:"za", group:"A", confederation:"CAF", fifaRanking:38, color:"#007a4d", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.6, goalsConceded:1.3, starPlayerValue:58, starPlayer:"L. Mokoena" },
  { id:3, name:"Corea del Sur", shortName:"KOR", flag:"🇰🇷", iso2:"kr", group:"A", confederation:"AFC", fifaRanking:19, color:"#cd2e3a", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2, goalsConceded:1, starPlayerValue:77, starPlayer:"Son Heung-min" },
  { id:4, name:"Chequia", shortName:"CZE", flag:"🇨🇿", iso2:"cz", group:"A", confederation:"UEFA", fifaRanking:43, color:"#11457e", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.5, goalsConceded:1.4, starPlayerValue:53, starPlayer:"P. Schick" },
  { id:5, name:"Canadá", shortName:"CAN", flag:"🇨🇦", iso2:"ca", group:"B", confederation:"CONCACAF", fifaRanking:31, color:"#ff0000", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.7, goalsConceded:1.2, starPlayerValue:65, starPlayer:"A. Davies" },
  { id:6, name:"Bosnia y Herzegovina", shortName:"BIH", flag:"🇧🇦", iso2:"ba", group:"B", confederation:"UEFA", fifaRanking:55, color:"#001f5b", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.2, goalsConceded:1.6, starPlayerValue:41, starPlayer:"E. Džeko" },
  { id:7, name:"Catar", shortName:"QAT", flag:"🇶🇦", iso2:"qa", group:"B", confederation:"AFC", fifaRanking:35, color:"#8a1538", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.6, goalsConceded:1.3, starPlayerValue:61, starPlayer:"A. Afif" },
  { id:8, name:"Suiza", shortName:"SUI", flag:"🇨🇭", iso2:"ch", group:"B", confederation:"UEFA", fifaRanking:16, color:"#d52b1e", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2, goalsConceded:1, starPlayerValue:80, starPlayer:"G. Xhaka" },
  { id:9, name:"Brasil", shortName:"BRA", flag:"🇧🇷", iso2:"br", group:"C", confederation:"CONMEBOL", fifaRanking:5, color:"#009c3b", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.3, goalsConceded:0.8, starPlayerValue:91, starPlayer:"Vinicius Jr" },
  { id:10, name:"Marruecos", shortName:"MAR", flag:"🇲🇦", iso2:"ma", group:"C", confederation:"CAF", fifaRanking:13, color:"#c1272d", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.1, goalsConceded:0.9, starPlayerValue:83, starPlayer:"A. Hakimi" },
  { id:11, name:"Haití", shortName:"HAI", flag:"🇭🇹", iso2:"ht", group:"C", confederation:"CONCACAF", fifaRanking:50, color:"#00209f", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.3, goalsConceded:1.5, starPlayerValue:46, starPlayer:"D. Pierrot" },
  { id:12, name:"Escocia", shortName:"SCO", flag:"🇬🇧", iso2:"gb-sct", group:"C", confederation:"UEFA", fifaRanking:30, color:"#005eb8", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.7, goalsConceded:1.2, starPlayerValue:66, starPlayer:"S. McTominay" },
  { id:13, name:"Estados Unidos", shortName:"USA", flag:"🇺🇸", iso2:"us", group:"D", confederation:"CONCACAF", fifaRanking:14, color:"#b22234", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.1, goalsConceded:0.9, starPlayerValue:82, starPlayer:"C. Pulisic" },
  { id:14, name:"Paraguay", shortName:"PAR", flag:"🇵🇾", iso2:"py", group:"D", confederation:"CONMEBOL", fifaRanking:29, color:"#d52b1e", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.8, goalsConceded:1.2, starPlayerValue:67, starPlayer:"M. Almirón" },
  { id:15, name:"Australia", shortName:"AUS", flag:"🇦🇺", iso2:"au", group:"D", confederation:"AFC", fifaRanking:23, color:"#00843d", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.9, goalsConceded:1.1, starPlayerValue:73, starPlayer:"M. Duke" },
  { id:16, name:"Turquía", shortName:"TUR", flag:"🇹🇷", iso2:"tr", group:"D", confederation:"UEFA", fifaRanking:25, color:"#e30a17", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.9, goalsConceded:1.1, starPlayerValue:71, starPlayer:"A. Güler" },
  { id:17, name:"Alemania", shortName:"GER", flag:"🇩🇪", iso2:"de", group:"E", confederation:"UEFA", fifaRanking:10, color:"#000000", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.2, goalsConceded:0.9, starPlayerValue:86, starPlayer:"J. Musiala" },
  { id:18, name:"Curazao", shortName:"CUW", flag:"🇨🇼", iso2:"cw", group:"E", confederation:"CONCACAF", fifaRanking:45, color:"#002b7f", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.4, goalsConceded:1.4, starPlayerValue:51, starPlayer:"L. Bacuna" },
  { id:19, name:"Costa de Marfil", shortName:"CIV", flag:"🇨🇮", iso2:"ci", group:"E", confederation:"CAF", fifaRanking:28, color:"#f77f00", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.8, goalsConceded:1.1, starPlayerValue:68, starPlayer:"S. Haller" },
  { id:20, name:"Ecuador", shortName:"ECU", flag:"🇪🇨", iso2:"ec", group:"E", confederation:"CONMEBOL", fifaRanking:21, color:"#ffdd00", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.9, goalsConceded:1, starPlayerValue:75, starPlayer:"M. Caicedo" },
  { id:21, name:"Países Bajos", shortName:"NED", flag:"🇳🇱", iso2:"nl", group:"F", confederation:"UEFA", fifaRanking:7, color:"#ff6f00", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.2, goalsConceded:0.8, starPlayerValue:89, starPlayer:"V. van Dijk" },
  { id:22, name:"Japón", shortName:"JPN", flag:"🇯🇵", iso2:"jp", group:"F", confederation:"AFC", fifaRanking:17, color:"#bc002d", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2, goalsConceded:1, starPlayerValue:79, starPlayer:"K. Mitoma" },
  { id:23, name:"Suecia", shortName:"SWE", flag:"🇸🇪", iso2:"se", group:"F", confederation:"UEFA", fifaRanking:27, color:"#006aa7", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.8, goalsConceded:1.1, starPlayerValue:69, starPlayer:"A. Isak" },
  { id:24, name:"Túnez", shortName:"TUN", flag:"🇹🇳", iso2:"tn", group:"F", confederation:"CAF", fifaRanking:36, color:"#e70013", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.6, goalsConceded:1.3, starPlayerValue:60, starPlayer:"Y. Msakni" },
  { id:25, name:"Bélgica", shortName:"BEL", flag:"🇧🇪", iso2:"be", group:"G", confederation:"UEFA", fifaRanking:8, color:"#e30613", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.2, goalsConceded:0.8, starPlayerValue:88, starPlayer:"K. De Bruyne" },
  { id:26, name:"Egipto", shortName:"EGY", flag:"🇪🇬", iso2:"eg", group:"G", confederation:"CAF", fifaRanking:24, color:"#ce1126", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.9, goalsConceded:1.1, starPlayerValue:72, starPlayer:"M. Salah" },
  { id:27, name:"Irán", shortName:"IRN", flag:"🇮🇷", iso2:"ir", group:"G", confederation:"AFC", fifaRanking:20, color:"#239f40", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2, goalsConceded:1, starPlayerValue:76, starPlayer:"M. Taremi" },
  { id:28, name:"Nueva Zelanda", shortName:"NZL", flag:"🇳🇿", iso2:"nz", group:"G", confederation:"OFC", fifaRanking:33, color:"#00247d", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.7, goalsConceded:1.2, starPlayerValue:63, starPlayer:"C. Wood" },
  { id:29, name:"España", shortName:"ESP", flag:"🇪🇸", iso2:"es", group:"H", confederation:"UEFA", fifaRanking:3, color:"#aa151b", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.3, goalsConceded:0.7, starPlayerValue:93, starPlayer:"Lamine Yamal" },
  { id:30, name:"Cabo Verde", shortName:"CPV", flag:"🇨🇻", iso2:"cv", group:"H", confederation:"CAF", fifaRanking:46, color:"#003893", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.4, goalsConceded:1.4, starPlayerValue:50, starPlayer:"R. Mendes" },
  { id:31, name:"Arabia Saudita", shortName:"KSA", flag:"🇸🇦", iso2:"sa", group:"H", confederation:"AFC", fifaRanking:44, color:"#006c35", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.4, goalsConceded:1.4, starPlayerValue:52, starPlayer:"S. Al-Dawsari" },
  { id:32, name:"Uruguay", shortName:"URU", flag:"🇺🇾", iso2:"uy", group:"H", confederation:"CONMEBOL", fifaRanking:12, color:"#5aaaff", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.1, goalsConceded:0.9, starPlayerValue:84, starPlayer:"F. Valverde" },
  { id:33, name:"Francia", shortName:"FRA", flag:"🇫🇷", iso2:"fr", group:"I", confederation:"UEFA", fifaRanking:2, color:"#0055a4", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.4, goalsConceded:0.7, starPlayerValue:94, starPlayer:"K. Mbappé" },
  { id:34, name:"Senegal", shortName:"SEN", flag:"🇸🇳", iso2:"sn", group:"I", confederation:"CAF", fifaRanking:18, color:"#00853f", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2, goalsConceded:1, starPlayerValue:78, starPlayer:"S. Mané" },
  { id:35, name:"Irak", shortName:"IRQ", flag:"🇮🇶", iso2:"iq", group:"I", confederation:"AFC", fifaRanking:43, color:"#007a3d", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.5, goalsConceded:1.4, starPlayerValue:53, starPlayer:"A. Hussein" },
  { id:36, name:"Noruega", shortName:"NOR", flag:"🇳🇴", iso2:"no", group:"I", confederation:"UEFA", fifaRanking:26, color:"#ba0c2f", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.8, goalsConceded:1.1, starPlayerValue:70, starPlayer:"E. Haaland" },
  { id:37, name:"Argentina", shortName:"ARG", flag:"🇦🇷", iso2:"ar", group:"J", confederation:"CONMEBOL", fifaRanking:1, color:"#74acdf", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.4, goalsConceded:0.7, starPlayerValue:95, starPlayer:"L. Messi" },
  { id:38, name:"Argelia", shortName:"ALG", flag:"🇩🇿", iso2:"dz", group:"J", confederation:"CAF", fifaRanking:37, color:"#006233", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.6, goalsConceded:1.3, starPlayerValue:59, starPlayer:"R. Mahrez" },
  { id:39, name:"Austria", shortName:"AUT", flag:"🇦🇹", iso2:"at", group:"J", confederation:"UEFA", fifaRanking:22, color:"#ed2939", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.9, goalsConceded:1.1, starPlayerValue:74, starPlayer:"M. Sabitzer" },
  { id:40, name:"Jordania", shortName:"JOR", flag:"🇯🇴", iso2:"jo", group:"J", confederation:"AFC", fifaRanking:40, color:"#007a3d", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.5, goalsConceded:1.3, starPlayerValue:56, starPlayer:"M. Al-Tamari" },
  { id:41, name:"Portugal", shortName:"POR", flag:"🇵🇹", iso2:"pt", group:"K", confederation:"UEFA", fifaRanking:6, color:"#006600", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.3, goalsConceded:0.8, starPlayerValue:90, starPlayer:"C. Ronaldo" },
  { id:42, name:"RD Congo", shortName:"COD", flag:"🇨🇩", iso2:"cd", group:"K", confederation:"CAF", fifaRanking:47, color:"#007fff", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.4, goalsConceded:1.5, starPlayerValue:49, starPlayer:"Y. Bolasie" },
  { id:43, name:"Uzbekistán", shortName:"UZB", flag:"🇺🇿", iso2:"uz", group:"K", confederation:"AFC", fifaRanking:39, color:"#1eb53a", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.5, goalsConceded:1.3, starPlayerValue:57, starPlayer:"E. Shomurodov" },
  { id:44, name:"Colombia", shortName:"COL", flag:"🇨🇴", iso2:"co", group:"K", confederation:"CONMEBOL", fifaRanking:11, color:"#fcd116", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.2, goalsConceded:0.9, starPlayerValue:85, starPlayer:"J. Rodríguez" },
  { id:45, name:"Inglaterra", shortName:"ENG", flag:"🇬🇧", iso2:"gb-eng", group:"L", confederation:"UEFA", fifaRanking:4, color:"#ffffff", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.3, goalsConceded:0.8, starPlayerValue:92, starPlayer:"J. Bellingham" },
  { id:46, name:"Croacia", shortName:"CRO", flag:"🇭🇷", iso2:"hr", group:"L", confederation:"UEFA", fifaRanking:9, color:"#ff0000", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:2.2, goalsConceded:0.8, starPlayerValue:87, starPlayer:"L. Modrić" },
  { id:47, name:"Ghana", shortName:"GHA", flag:"🇬🇭", iso2:"gh", group:"L", confederation:"CAF", fifaRanking:48, color:"#006b3f", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.3, goalsConceded:1.5, starPlayerValue:48, starPlayer:"M. Kudus" },
  { id:48, name:"Panamá", shortName:"PAN", flag:"🇵🇦", iso2:"pa", group:"L", confederation:"CONCACAF", fifaRanking:32, color:"#da121a", recentForm:["W","D","W","L","W","D","W","W","D","W"], goalsScored:1.7, goalsConceded:1.2, starPlayerValue:64, starPlayer:"A. Carrasquilla" },
];

// ——— FIXTURES REALES (72 partidos de fase de grupos) ———
// utc: hora oficial en UTC. homeGoals/awayGoals: null = no jugado.
const FIXTURES = [
  { id:1, group:"A", matchday:1, utc:"2026-06-11T19:00:00Z", home:"MEX", away:"RSA", homeGoals:null, awayGoals:null },
  { id:2, group:"A", matchday:1, utc:"2026-06-12T02:00:00Z", home:"KOR", away:"CZE", homeGoals:null, awayGoals:null },
  { id:3, group:"A", matchday:2, utc:"2026-06-18T16:00:00Z", home:"CZE", away:"RSA", homeGoals:null, awayGoals:null },
  { id:4, group:"A", matchday:2, utc:"2026-06-19T01:00:00Z", home:"MEX", away:"KOR", homeGoals:null, awayGoals:null },
  { id:5, group:"A", matchday:3, utc:"2026-06-25T01:00:00Z", home:"CZE", away:"MEX", homeGoals:null, awayGoals:null },
  { id:6, group:"A", matchday:3, utc:"2026-06-25T01:00:00Z", home:"RSA", away:"KOR", homeGoals:null, awayGoals:null },
  { id:7, group:"B", matchday:1, utc:"2026-06-12T19:00:00Z", home:"CAN", away:"BIH", homeGoals:null, awayGoals:null },
  { id:8, group:"B", matchday:1, utc:"2026-06-13T19:00:00Z", home:"QAT", away:"SUI", homeGoals:null, awayGoals:null },
  { id:9, group:"B", matchday:2, utc:"2026-06-18T19:00:00Z", home:"SUI", away:"BIH", homeGoals:null, awayGoals:null },
  { id:10, group:"B", matchday:2, utc:"2026-06-18T22:00:00Z", home:"CAN", away:"QAT", homeGoals:null, awayGoals:null },
  { id:11, group:"B", matchday:3, utc:"2026-06-24T19:00:00Z", home:"BIH", away:"QAT", homeGoals:null, awayGoals:null },
  { id:12, group:"B", matchday:3, utc:"2026-06-24T19:00:00Z", home:"SUI", away:"CAN", homeGoals:null, awayGoals:null },
  { id:13, group:"C", matchday:1, utc:"2026-06-13T22:00:00Z", home:"BRA", away:"MAR", homeGoals:null, awayGoals:null },
  { id:14, group:"C", matchday:1, utc:"2026-06-14T01:00:00Z", home:"HAI", away:"SCO", homeGoals:null, awayGoals:null },
  { id:15, group:"C", matchday:2, utc:"2026-06-19T22:00:00Z", home:"SCO", away:"MAR", homeGoals:null, awayGoals:null },
  { id:16, group:"C", matchday:2, utc:"2026-06-20T01:00:00Z", home:"BRA", away:"HAI", homeGoals:null, awayGoals:null },
  { id:17, group:"C", matchday:3, utc:"2026-06-24T22:00:00Z", home:"SCO", away:"BRA", homeGoals:null, awayGoals:null },
  { id:18, group:"C", matchday:3, utc:"2026-06-24T22:00:00Z", home:"MAR", away:"HAI", homeGoals:null, awayGoals:null },
  { id:19, group:"D", matchday:1, utc:"2026-06-13T01:00:00Z", home:"USA", away:"PAR", homeGoals:null, awayGoals:null },
  { id:20, group:"D", matchday:1, utc:"2026-06-14T04:00:00Z", home:"AUS", away:"TUR", homeGoals:null, awayGoals:null },
  { id:21, group:"D", matchday:2, utc:"2026-06-19T19:00:00Z", home:"USA", away:"AUS", homeGoals:null, awayGoals:null },
  { id:22, group:"D", matchday:2, utc:"2026-06-20T03:00:00Z", home:"TUR", away:"PAR", homeGoals:null, awayGoals:null },
  { id:23, group:"D", matchday:3, utc:"2026-06-26T02:00:00Z", home:"PAR", away:"AUS", homeGoals:null, awayGoals:null },
  { id:24, group:"D", matchday:3, utc:"2026-06-26T02:00:00Z", home:"TUR", away:"USA", homeGoals:null, awayGoals:null },
  { id:25, group:"E", matchday:1, utc:"2026-06-14T17:00:00Z", home:"GER", away:"CUW", homeGoals:null, awayGoals:null },
  { id:26, group:"E", matchday:1, utc:"2026-06-14T23:00:00Z", home:"CIV", away:"ECU", homeGoals:null, awayGoals:null },
  { id:27, group:"E", matchday:2, utc:"2026-06-20T20:00:00Z", home:"GER", away:"CIV", homeGoals:null, awayGoals:null },
  { id:28, group:"E", matchday:2, utc:"2026-06-21T00:00:00Z", home:"ECU", away:"CUW", homeGoals:null, awayGoals:null },
  { id:29, group:"E", matchday:3, utc:"2026-06-25T20:00:00Z", home:"CUW", away:"CIV", homeGoals:null, awayGoals:null },
  { id:30, group:"E", matchday:3, utc:"2026-06-25T20:00:00Z", home:"ECU", away:"GER", homeGoals:null, awayGoals:null },
  { id:31, group:"F", matchday:1, utc:"2026-06-14T20:00:00Z", home:"NED", away:"JPN", homeGoals:null, awayGoals:null },
  { id:32, group:"F", matchday:1, utc:"2026-06-15T02:00:00Z", home:"SWE", away:"TUN", homeGoals:null, awayGoals:null },
  { id:33, group:"F", matchday:2, utc:"2026-06-20T17:00:00Z", home:"NED", away:"SWE", homeGoals:null, awayGoals:null },
  { id:34, group:"F", matchday:2, utc:"2026-06-21T04:00:00Z", home:"TUN", away:"JPN", homeGoals:null, awayGoals:null },
  { id:35, group:"F", matchday:3, utc:"2026-06-25T23:00:00Z", home:"JPN", away:"SWE", homeGoals:null, awayGoals:null },
  { id:36, group:"F", matchday:3, utc:"2026-06-25T23:00:00Z", home:"TUN", away:"NED", homeGoals:null, awayGoals:null },
  { id:37, group:"G", matchday:1, utc:"2026-06-15T19:00:00Z", home:"BEL", away:"EGY", homeGoals:null, awayGoals:null },
  { id:38, group:"G", matchday:1, utc:"2026-06-16T01:00:00Z", home:"IRN", away:"NZL", homeGoals:null, awayGoals:null },
  { id:39, group:"G", matchday:2, utc:"2026-06-21T19:00:00Z", home:"BEL", away:"IRN", homeGoals:null, awayGoals:null },
  { id:40, group:"G", matchday:2, utc:"2026-06-22T01:00:00Z", home:"NZL", away:"EGY", homeGoals:null, awayGoals:null },
  { id:41, group:"G", matchday:3, utc:"2026-06-27T03:00:00Z", home:"NZL", away:"BEL", homeGoals:null, awayGoals:null },
  { id:42, group:"G", matchday:3, utc:"2026-06-27T03:00:00Z", home:"EGY", away:"IRN", homeGoals:null, awayGoals:null },
  { id:43, group:"H", matchday:1, utc:"2026-06-15T16:00:00Z", home:"ESP", away:"CPV", homeGoals:null, awayGoals:null },
  { id:44, group:"H", matchday:1, utc:"2026-06-15T22:00:00Z", home:"KSA", away:"URU", homeGoals:null, awayGoals:null },
  { id:45, group:"H", matchday:2, utc:"2026-06-21T16:00:00Z", home:"ESP", away:"KSA", homeGoals:null, awayGoals:null },
  { id:46, group:"H", matchday:2, utc:"2026-06-21T22:00:00Z", home:"URU", away:"CPV", homeGoals:null, awayGoals:null },
  { id:47, group:"H", matchday:3, utc:"2026-06-27T00:00:00Z", home:"CPV", away:"KSA", homeGoals:null, awayGoals:null },
  { id:48, group:"H", matchday:3, utc:"2026-06-27T00:00:00Z", home:"URU", away:"ESP", homeGoals:null, awayGoals:null },
  { id:49, group:"I", matchday:1, utc:"2026-06-16T19:00:00Z", home:"FRA", away:"SEN", homeGoals:null, awayGoals:null },
  { id:50, group:"I", matchday:1, utc:"2026-06-16T22:00:00Z", home:"IRQ", away:"NOR", homeGoals:null, awayGoals:null },
  { id:51, group:"I", matchday:2, utc:"2026-06-22T21:00:00Z", home:"FRA", away:"IRQ", homeGoals:null, awayGoals:null },
  { id:52, group:"I", matchday:2, utc:"2026-06-23T00:00:00Z", home:"NOR", away:"SEN", homeGoals:null, awayGoals:null },
  { id:53, group:"I", matchday:3, utc:"2026-06-26T19:00:00Z", home:"NOR", away:"FRA", homeGoals:null, awayGoals:null },
  { id:54, group:"I", matchday:3, utc:"2026-06-26T19:00:00Z", home:"SEN", away:"IRQ", homeGoals:null, awayGoals:null },
  { id:55, group:"J", matchday:1, utc:"2026-06-17T01:00:00Z", home:"ARG", away:"ALG", homeGoals:null, awayGoals:null },
  { id:56, group:"J", matchday:1, utc:"2026-06-17T04:00:00Z", home:"AUT", away:"JOR", homeGoals:null, awayGoals:null },
  { id:57, group:"J", matchday:2, utc:"2026-06-22T17:00:00Z", home:"ARG", away:"AUT", homeGoals:null, awayGoals:null },
  { id:58, group:"J", matchday:2, utc:"2026-06-23T03:00:00Z", home:"JOR", away:"ALG", homeGoals:null, awayGoals:null },
  { id:59, group:"J", matchday:3, utc:"2026-06-28T02:00:00Z", home:"ALG", away:"AUT", homeGoals:null, awayGoals:null },
  { id:60, group:"J", matchday:3, utc:"2026-06-28T02:00:00Z", home:"JOR", away:"ARG", homeGoals:null, awayGoals:null },
  { id:61, group:"K", matchday:1, utc:"2026-06-17T17:00:00Z", home:"POR", away:"COD", homeGoals:null, awayGoals:null },
  { id:62, group:"K", matchday:1, utc:"2026-06-18T02:00:00Z", home:"UZB", away:"COL", homeGoals:null, awayGoals:null },
  { id:63, group:"K", matchday:2, utc:"2026-06-23T17:00:00Z", home:"POR", away:"UZB", homeGoals:null, awayGoals:null },
  { id:64, group:"K", matchday:2, utc:"2026-06-24T02:00:00Z", home:"COL", away:"COD", homeGoals:null, awayGoals:null },
  { id:65, group:"K", matchday:3, utc:"2026-06-27T23:30:00Z", home:"COL", away:"POR", homeGoals:null, awayGoals:null },
  { id:66, group:"K", matchday:3, utc:"2026-06-27T23:30:00Z", home:"COD", away:"UZB", homeGoals:null, awayGoals:null },
  { id:67, group:"L", matchday:1, utc:"2026-06-17T20:00:00Z", home:"ENG", away:"CRO", homeGoals:null, awayGoals:null },
  { id:68, group:"L", matchday:1, utc:"2026-06-17T23:00:00Z", home:"GHA", away:"PAN", homeGoals:null, awayGoals:null },
  { id:69, group:"L", matchday:2, utc:"2026-06-23T20:00:00Z", home:"ENG", away:"GHA", homeGoals:null, awayGoals:null },
  { id:70, group:"L", matchday:2, utc:"2026-06-23T23:00:00Z", home:"PAN", away:"CRO", homeGoals:null, awayGoals:null },
  { id:71, group:"L", matchday:3, utc:"2026-06-27T21:00:00Z", home:"CRO", away:"GHA", homeGoals:null, awayGoals:null },
  { id:72, group:"L", matchday:3, utc:"2026-06-27T21:00:00Z", home:"PAN", away:"ENG", homeGoals:null, awayGoals:null },
];

// ——— CUOTAS DE CAMPEÓN (DoradoBet simulado) ———
const DORADOBET_ODDS = {
  ARG: { odds: 3.50,  impliedProb: 28.57 },
  FRA: { odds: 4.50,  impliedProb: 22.22 },
  BRA: { odds: 5.50,  impliedProb: 18.18 },
  ENG: { odds: 6.50,  impliedProb: 15.38 },
  ESP: { odds: 9.00,  impliedProb: 11.11 },
  GER: { odds: 11.00, impliedProb: 9.09  },
  POR: { odds: 12.00, impliedProb: 8.33  },
  NED: { odds: 15.00, impliedProb: 6.67  },
  CRO: { odds: 22.00, impliedProb: 4.55  },
  COL: { odds: 28.00, impliedProb: 3.57  },
  URU: { odds: 30.00, impliedProb: 3.33  },
  MAR: { odds: 35.00, impliedProb: 2.86  },
  SEN: { odds: 40.00, impliedProb: 2.50  },
  SUI: { odds: 45.00, impliedProb: 2.22  },
  TUR: { odds: 50.00, impliedProb: 2.00  },
  JPN: { odds: 50.00, impliedProb: 2.00  },
  KOR: { odds: 55.00, impliedProb: 1.82  },
  AUT: { odds: 60.00, impliedProb: 1.67  },
  DEN: { odds: 65.00, impliedProb: 1.54  },
  EGY: { odds: 70.00, impliedProb: 1.43  },
  SRB: { odds: 75.00, impliedProb: 1.33  },
  USA: { odds: 80.00, impliedProb: 1.25  },
  MEX: { odds: 85.00, impliedProb: 1.18  },
  ECU: { odds: 90.00, impliedProb: 1.11  },
  NGA: { odds: 95.00, impliedProb: 1.05  },
  IRN: { odds:100.00, impliedProb: 1.00  },
  POL: { odds:110.00, impliedProb: 0.91  },
  CAN: { odds:120.00, impliedProb: 0.83  },
  AUS: { odds:130.00, impliedProb: 0.77  },
  CMR: { odds:140.00, impliedProb: 0.71  },
  GHA: { odds:160.00, impliedProb: 0.63  },
  HUN: { odds:175.00, impliedProb: 0.57  },
  CIV: { odds:200.00, impliedProb: 0.50  },
  VEN: { odds:200.00, impliedProb: 0.50  },
  UZB: { odds:250.00, impliedProb: 0.40  },
  BEL: { odds:260.00, impliedProb: 0.38  },
  KSA: { odds:300.00, impliedProb: 0.33  },
  RSA: { odds:350.00, impliedProb: 0.29  },
  JOR: { odds:400.00, impliedProb: 0.25  },
  TUN: { odds:400.00, impliedProb: 0.25  },
  HON: { odds:500.00, impliedProb: 0.20  },
  PAN: { odds:500.00, impliedProb: 0.20  },
  ALB: { odds:550.00, impliedProb: 0.18  },
  COD: { odds:600.00, impliedProb: 0.17  },
  NZL: { odds:700.00, impliedProb: 0.14  },
  QAT: { odds:750.00, impliedProb: 0.13  },
  JAM: { odds:800.00, impliedProb: 0.13  },
  SCO: { odds:850.00, impliedProb: 0.12  },
};

const GROUPS = ["A","B","C","D","E","F","G","H","I","J","K","L"];
