// ============================================================
//  SQUADS.JS — Plantillas Convocadas Mundial 2026
//  Datos: estimados pre-torneo (actualizar con listas oficiales FIFA)
//  Posiciones: GK | RB | CB | LB | DM | CM | RM | LM | AM | CF | ST
// ============================================================

const SQUADS = {

  // ── GRUPO A ──────────────────────────────────────────────────

  USA: {
    coach: "Mauricio Pochettino",
    players: [
      { n:1,  name:"Matt Turner",        pos:"GK", club:"Crystal Palace",     caps:40, age:30 },
      { n:13, name:"Ethan Horvath",      pos:"GK", club:"Cardiff City",       caps:18, age:28 },
      { n:23, name:"Patrick Schulte",    pos:"GK", club:"Columbus Crew",      caps:4,  age:24 },
      { n:2,  name:"Sergiño Dest",       pos:"RB", club:"PSV Eindhoven",      caps:38, age:24 },
      { n:3,  name:"Joe Scally",         pos:"RB", club:"Gladbach",           caps:22, age:22 },
      { n:4,  name:"Tyler Adams",        pos:"DM", club:"Bournemouth",        caps:52, age:26 },
      { n:5,  name:"Walker Zimmerman",   pos:"CB", club:"Nashville SC",       caps:35, age:31 },
      { n:6,  name:"Yunus Musah",        pos:"CM", club:"AC Milan",           caps:45, age:22 },
      { n:7,  name:"Giovanni Reyna",     pos:"AM", club:"Nottingham Forest",  caps:36, age:22 },
      { n:8,  name:"Weston McKennie",    pos:"CM", club:"Juventus",           caps:55, age:26 },
      { n:9,  name:"Josh Sargent",       pos:"ST", club:"Norwich City",       caps:38, age:25 },
      { n:10, name:"Christian Pulisic",  pos:"AM", club:"AC Milan",           caps:68, age:26 },
      { n:11, name:"Tim Weah",           pos:"RM", club:"Juventus",           caps:42, age:25 },
      { n:12, name:"Antonee Robinson",   pos:"LB", club:"Fulham",             caps:50, age:27 },
      { n:14, name:"Luca de la Torre",   pos:"CM", club:"Celta Vigo",         caps:28, age:27 },
      { n:15, name:"Mark McKenzie",      pos:"CB", club:"Toulouse",           caps:24, age:25 },
      { n:16, name:"Joe Benson",         pos:"LM", club:"Burnley",            caps:12, age:22 },
      { n:17, name:"Jordan Morris",      pos:"ST", club:"Seattle Sounders",   caps:62, age:30 },
      { n:18, name:"Folarin Balogun",    pos:"CF", club:"Monaco",             caps:30, age:24 },
      { n:19, name:"Ricardo Pepi",       pos:"ST", club:"PSV Eindhoven",      caps:28, age:22 },
      { n:20, name:"Reggie Cannon",      pos:"RB", club:"Boavista",           caps:35, age:26 },
      { n:21, name:"Miles Robinson",     pos:"CB", club:"FC Cincinnati",      caps:22, age:27 },
      { n:22, name:"Jesús Ferreira",     pos:"CF", club:"FC Dallas",          caps:30, age:24 },
    ],
  },

  PAN: {
    coach: "Thomas Christiansen",
    players: [
      { n:1,  name:"Luis Mejía",         pos:"GK", club:"Olimpia",            caps:55, age:30 },
      { n:13, name:"José Calderón",      pos:"GK", club:"FC Dallas",          caps:15, age:27 },
      { n:23, name:"Orlando Mosquera",   pos:"GK", club:"Junior",             caps:8,  age:24 },
      { n:2,  name:"Eric Davis",         pos:"RB", club:"Columbus Crew",      caps:60, age:34 },
      { n:3,  name:"Harold Cummings",    pos:"CB", club:"Sporting KC",        caps:58, age:29 },
      { n:4,  name:"Adalberto Carrasquilla", pos:"CM", club:"Houston Dynamo",caps:68, age:26 },
      { n:5,  name:"César Yanis",        pos:"CB", club:"Unión La Calera",    caps:32, age:28 },
      { n:6,  name:"José Fajardo",       pos:"ST", club:"Philadelphia Union", caps:42, age:28 },
      { n:7,  name:"Alfredo Morelos",    pos:"ST", club:"Racing Club",        caps:35, age:28 },
      { n:8,  name:"Rolando Blackburn",  pos:"ST", club:"Panamá Viejo",       caps:40, age:28 },
      { n:9,  name:"Gabriel Torres",     pos:"CF", club:"Olimpia",            caps:65, age:35 },
      { n:10, name:"Aníbal Godoy",       pos:"DM", club:"Nashville SC",       caps:90, age:34 },
      { n:11, name:"Abdiel Ayarza",      pos:"LM", club:"Herediano",          caps:30, age:27 },
      { n:12, name:"Gianluca Busio",     pos:"CM", club:"Venezia",            caps:22, age:23 },
      { n:14, name:"Andrés Andrade",     pos:"RM", club:"CD Lugo",            caps:45, age:29 },
      { n:15, name:"Édgar Bárcenas",     pos:"LM", club:"Coras",              caps:38, age:28 },
      { n:16, name:"Armando Cooper",     pos:"CM", club:"LAFC",               caps:50, age:32 },
      { n:17, name:"Iván Anderson",      pos:"RB", club:"Unión La Calera",    caps:28, age:25 },
      { n:18, name:"Michael Murillo",    pos:"RB", club:"Anderlecht",         caps:50, age:28 },
      { n:19, name:"Cecilio Waterman",   pos:"ST", club:"Miami FC",           caps:45, age:30 },
      { n:20, name:"Roberto Nurse",      pos:"LB", club:"CD Vida",            caps:35, age:28 },
      { n:21, name:"Fidel Escobar",      pos:"CB", club:"New England Rev.",   caps:55, age:28 },
      { n:22, name:"Alán Santamaría",    pos:"DM", club:"San José Earthquakes",caps:20,age:24 },
    ],
  },

  URU: {
    coach: "Marcelo Bielsa",
    players: [
      { n:1,  name:"Sergio Rochet",      pos:"GK", club:"Nacional",           caps:45, age:30 },
      { n:13, name:"Sebastián Sosa",     pos:"GK", club:"Independiente",      caps:18, age:37 },
      { n:23, name:"Mathías Laborda",    pos:"GK", club:"Cerro Largo",        caps:5,  age:26 },
      { n:2,  name:"Nahitan Nández",     pos:"RB", club:"Cagliari",           caps:55, age:28 },
      { n:3,  name:"Mathías Olivera",    pos:"LB", club:"Napoli",             caps:40, age:27 },
      { n:4,  name:"Lucas Torreira",     pos:"DM", club:"Galatasaray",        caps:65, age:28 },
      { n:5,  name:"Diego Godín",        pos:"CB", club:"Nacional",           caps:160, age:38 },
      { n:6,  name:"Ronald Araújo",      pos:"CB", club:"Atletico Madrid",    caps:50, age:25 },
      { n:7,  name:"Giorgian de Arrascaeta", pos:"AM", club:"Flamengo",      caps:55, age:30 },
      { n:8,  name:"Federico Valverde",  pos:"CM", club:"Real Madrid",        caps:65, age:26 },
      { n:9,  name:"Darwin Núñez",       pos:"ST", club:"Liverpool",          caps:48, age:25 },
      { n:10, name:"Rodrigo Bentancur",  pos:"CM", club:"Tottenham",          caps:58, age:27 },
      { n:11, name:"Facundo Torres",     pos:"AM", club:"Orlando City",       caps:30, age:24 },
      { n:12, name:"José María Giménez", pos:"CB", club:"Atletico Madrid",    caps:72, age:30 },
      { n:14, name:"Maxi Gómez",         pos:"ST", club:"Trabzonspor",        caps:38, age:28 },
      { n:15, name:"Brian Rodríguez",    pos:"LM", club:"LAFC",               caps:35, age:24 },
      { n:16, name:"Sebastián Coates",   pos:"CB", club:"Sporting CP",        caps:55, age:33 },
      { n:17, name:"Gastón Pereiro",     pos:"AM", club:"Real Betis",         caps:38, age:29 },
      { n:18, name:"Luis Suárez",        pos:"ST", club:"Retiro",             caps:140, age:39 },
      { n:19, name:"Edinson Cavani",     pos:"ST", club:"Boca Juniors",       caps:136, age:37 },
      { n:20, name:"Diego Rossi",        pos:"LM", club:"Fenerbahce",         caps:22, age:25 },
      { n:21, name:"Matías Vecino",      pos:"CM", club:"Lazio",              caps:78, age:33 },
      { n:22, name:"José Luis Rodríguez",pos:"RB", club:"Nacional",           caps:15, age:23 },
    ],
  },

  MAR: {
    coach: "Walid Regragui",
    players: [
      { n:1,  name:"Yassine Bounou",     pos:"GK", club:"Al-Hilal",           caps:55, age:33 },
      { n:13, name:"Munir el-Kajoui",    pos:"GK", club:"Al-Shabab",          caps:18, age:32 },
      { n:23, name:"Ahmed Reda Tagnaouti", pos:"GK", club:"Wydad",            caps:8,  age:28 },
      { n:2,  name:"Achraf Hakimi",      pos:"RB", club:"PSG",                caps:80, age:26 },
      { n:3,  name:"Noussair Mazraoui",  pos:"RB", club:"Man Utd",            caps:52, age:27 },
      { n:4,  name:"Romain Saïss",       pos:"CB", club:"Besiktas",           caps:80, age:34 },
      { n:5,  name:"Nayef Aguerd",       pos:"CB", club:"West Ham",           caps:40, age:28 },
      { n:6,  name:"Sofyan Amrabat",     pos:"DM", club:"Fiorentina",         caps:60, age:28 },
      { n:7,  name:"Hakim Ziyech",       pos:"AM", club:"Galatasaray",        caps:68, age:32 },
      { n:8,  name:"Azzedine Ounahi",    pos:"CM", club:"OM Marseille",       caps:38, age:24 },
      { n:9,  name:"Youssef En-Nesyri",  pos:"ST", club:"Fenerbahce",         caps:62, age:27 },
      { n:10, name:"Brahim Díaz",        pos:"AM", club:"Real Madrid",        caps:25, age:25 },
      { n:11, name:"Yassine Ziyech",     pos:"LM", club:"Galatasaray",        caps:15, age:23 },
      { n:12, name:"Yahia Attiat-Allah", pos:"LB", club:"Wydad",              caps:25, age:27 },
      { n:14, name:"Selim Amallah",      pos:"CM", club:"Standard Liège",     caps:30, age:26 },
      { n:15, name:"Badr Benoun",        pos:"CB", club:"Al-Qadsiah",         caps:20, age:28 },
      { n:16, name:"Amine Harit",        pos:"AM", club:"OM Marseille",       caps:30, age:27 },
      { n:17, name:"Jawad El Yamiq",     pos:"CB", club:"Real Betis",         caps:35, age:30 },
      { n:18, name:"Walid Cheddira",     pos:"ST", club:"Parma",              caps:20, age:26 },
      { n:19, name:"Abdessamad Ezzalzouli", pos:"LM", club:"Real Betis",      caps:15, age:23 },
      { n:20, name:"Ilias Chair",        pos:"AM", club:"Leicester City",     caps:22, age:27 },
      { n:21, name:"Zakaria Aboukhlal",  pos:"ST", club:"Toulouse",           caps:28, age:23 },
      { n:22, name:"Adam Masina",        pos:"LB", club:"Watford",            caps:22, age:30 },
    ],
  },

  // ── GRUPO B ──────────────────────────────────────────────────

  MEX: {
    coach: "Javier Aguirre",
    players: [
      { n:1,  name:"Guillermo Ochoa",    pos:"GK", club:"América",            caps:145, age:39 },
      { n:13, name:"Luis Malagón",       pos:"GK", club:"América",            caps:20, age:27 },
      { n:23, name:"Carlos Acevedo",     pos:"GK", club:"Santos Laguna",      caps:10, age:27 },
      { n:2,  name:"Jorge Sánchez",      pos:"RB", club:"Porto",              caps:45, age:26 },
      { n:3,  name:"Jesús Gallardo",     pos:"LB", club:"Monterrey",          caps:70, age:29 },
      { n:4,  name:"Edson Álvarez",      pos:"DM", club:"West Ham",           caps:75, age:27 },
      { n:5,  name:"Johan Vásquez",      pos:"CB", club:"Genoa",              caps:35, age:25 },
      { n:6,  name:"César Montes",       pos:"CB", club:"Espanyol",           caps:55, age:27 },
      { n:7,  name:"Hirving Lozano",     pos:"RM", club:"PSV Eindhoven",      caps:90, age:29 },
      { n:8,  name:"Carlos Rodríguez",   pos:"CM", club:"Cruz Azul",          caps:45, age:28 },
      { n:9,  name:"Raúl Jiménez",       pos:"ST", club:"Fulham",             caps:110, age:33 },
      { n:10, name:"Alexis Vega",        pos:"AM", club:"Guadalajara",        caps:42, age:27 },
      { n:11, name:"Orbelín Pineda",     pos:"AM", club:"AEK Athens",         caps:52, age:28 },
      { n:12, name:"Julián Araujo",      pos:"RB", club:"Barcelona",          caps:22, age:23 },
      { n:14, name:"Roberto Alvarado",   pos:"CM", club:"Guadalajara",        caps:38, age:25 },
      { n:15, name:"Jorge Ruvalcaba",    pos:"CM", club:"Pachuca",            caps:15, age:25 },
      { n:16, name:"Santiago Giménez",   pos:"ST", club:"Feyenoord",          caps:40, age:23 },
      { n:17, name:"Chucky Lozano",      pos:"RM", club:"PSV Eindhoven",      caps:90, age:29 },
      { n:18, name:"Henry Martín",       pos:"ST", club:"América",            caps:35, age:31 },
      { n:19, name:"Luis Romo",          pos:"CM", club:"Cruz Azul",          caps:42, age:29 },
      { n:20, name:"Néstor Araujo",      pos:"CB", club:"América",            caps:60, age:32 },
      { n:21, name:"Erick Gutiérrez",    pos:"CM", club:"PSV Eindhoven",      caps:55, age:29 },
      { n:22, name:"Uriel Antuna",       pos:"LM", club:"Cruz Azul",          caps:38, age:26 },
    ],
  },

  // ── GRUPO D ──────────────────────────────────────────────────

  ARG: {
    coach: "Lionel Scaloni",
    players: [
      { n:1,  name:"Emiliano Martínez",  pos:"GK", club:"Aston Villa",        caps:52, age:32 },
      { n:12, name:"Agustín Marchesín",  pos:"GK", club:"Genoa",              caps:12, age:35 },
      { n:23, name:"Gerónimo Rulli",     pos:"GK", club:"Ajax",               caps:20, age:32 },
      { n:2,  name:"Gonzalo Montiel",    pos:"RB", club:"Sevilla",            caps:35, age:27 },
      { n:3,  name:"Nicolás Tagliafico", pos:"LB", club:"Lyon",               caps:68, age:32 },
      { n:4,  name:"Gonzalo Montiel",    pos:"RB", club:"Nottingham Forest",  caps:35, age:27 },
      { n:5,  name:"Leandro Paredes",    pos:"DM", club:"Roma",               caps:68, age:30 },
      { n:6,  name:"Germán Pezzella",    pos:"CB", club:"Real Betis",         caps:25, age:33 },
      { n:7,  name:"Rodrigo De Paul",    pos:"CM", club:"Atletico Madrid",    caps:72, age:30 },
      { n:8,  name:"Marcos Acuña",       pos:"LB", club:"Sevilla",            caps:58, age:32 },
      { n:9,  name:"Julián Álvarez",     pos:"CF", club:"Atletico Madrid",    caps:48, age:25 },
      { n:10, name:"Lionel Messi",       pos:"AM", club:"Inter Miami",        caps:185, age:38 },
      { n:11, name:"Ángel Di María",     pos:"LM", club:"Benfica",            caps:140, age:36 },
      { n:13, name:"Cristian Romero",    pos:"CB", club:"Tottenham",          caps:52, age:26 },
      { n:14, name:"Exequiel Palacios",  pos:"CM", club:"Bayer Leverkusen",   caps:28, age:26 },
      { n:15, name:"Nicolás Otamendi",   pos:"CB", club:"Benfica",            caps:110, age:37 },
      { n:16, name:"Thiago Almada",      pos:"AM", club:"Lyon",               caps:20, age:23 },
      { n:17, name:"Alejandro Garnacho", pos:"LM", club:"Man Utd",            caps:22, age:21 },
      { n:18, name:"Guido Rodríguez",    pos:"DM", club:"Real Betis",         caps:40, age:30 },
      { n:19, name:"Nicolás González",   pos:"LM", club:"Juventus",           caps:30, age:26 },
      { n:20, name:"Lautaro Martínez",   pos:"ST", club:"Inter Milan",        caps:72, age:27 },
      { n:21, name:"Paulo Dybala",       pos:"AM", club:"Roma",               caps:40, age:31 },
      { n:22, name:"Enzo Fernández",     pos:"CM", club:"Chelsea",            caps:42, age:24 },
    ],
  },

  ESP: {
    coach: "Luis de la Fuente",
    players: [
      { n:1,  name:"David Raya",         pos:"GK", club:"Arsenal",            caps:28, age:29 },
      { n:13, name:"Unai Simón",         pos:"GK", club:"Athletic Bilbao",    caps:40, age:27 },
      { n:23, name:"Alex Remiro",        pos:"GK", club:"Real Sociedad",      caps:18, age:29 },
      { n:2,  name:"Dani Carvajal",      pos:"RB", club:"Real Madrid",        caps:95, age:33 },
      { n:3,  name:"Alejandro Balde",    pos:"LB", club:"FC Barcelona",       caps:25, age:21 },
      { n:4,  name:"Rodrigo Hernández",  pos:"DM", club:"Man City",           caps:42, age:23 },
      { n:5,  name:"Aymeric Laporte",    pos:"CB", club:"Real Madrid",        caps:38, age:30 },
      { n:6,  name:"Mikel Merino",       pos:"CM", club:"Arsenal",            caps:35, age:28 },
      { n:7,  name:"Álvaro Morata",      pos:"ST", club:"AC Milan",           caps:72, age:32 },
      { n:8,  name:"Koke",              pos:"CM", club:"Atletico Madrid",    caps:90, age:32 },
      { n:9,  name:"Joselu",             pos:"ST", club:"Real Madrid",        caps:22, age:34 },
      { n:10, name:"Dani Olmo",          pos:"AM", club:"FC Barcelona",       caps:42, age:26 },
      { n:11, name:"Ferran Torres",      pos:"LM", club:"FC Barcelona",       caps:45, age:25 },
      { n:12, name:"Marc Cucurella",     pos:"LB", club:"Chelsea",            caps:30, age:26 },
      { n:14, name:"Fabián Ruiz",        pos:"CM", club:"PSG",                caps:32, age:28 },
      { n:15, name:"Dani Vivian",        pos:"CB", club:"Athletic Bilbao",    caps:15, age:25 },
      { n:16, name:"Álex Grimaldo",      pos:"LB", club:"Bayer Leverkusen",   caps:12, age:29 },
      { n:17, name:"Nico Williams",      pos:"LM", club:"Athletic Bilbao",    caps:22, age:22 },
      { n:18, name:"Martín Zubimendi",   pos:"DM", club:"Real Sociedad",      caps:18, age:25 },
      { n:19, name:"Lamine Yamal",       pos:"RM", club:"FC Barcelona",       caps:18, age:17 },
      { n:20, name:"Pedri",              pos:"CM", club:"FC Barcelona",       caps:35, age:22 },
      { n:21, name:"Mikel Oyarzabal",    pos:"ST", club:"Real Sociedad",      caps:38, age:27 },
      { n:22, name:"Robin Le Normand",   pos:"CB", club:"Atletico Madrid",    caps:20, age:28 },
    ],
  },

  // ── GRUPO E ──────────────────────────────────────────────────

  BRA: {
    coach: "Dorival Júnior",
    players: [
      { n:1,  name:"Alisson",            pos:"GK", club:"Liverpool",          caps:75, age:32 },
      { n:12, name:"Ederson",            pos:"GK", club:"Man City",           caps:38, age:31 },
      { n:23, name:"Bento",              pos:"GK", club:"Al-Qadsiah",         caps:20, age:25 },
      { n:2,  name:"Danilo",             pos:"RB", club:"Juventus",           caps:75, age:33 },
      { n:3,  name:"Wendell",            pos:"LB", club:"Porto",              caps:20, age:30 },
      { n:4,  name:"Marquinhos",         pos:"CB", club:"PSG",                caps:82, age:30 },
      { n:5,  name:"Casemiro",           pos:"DM", club:"Man Utd",            caps:72, age:33 },
      { n:6,  name:"Alex Telles",        pos:"LB", club:"Sevilla",            caps:32, age:32 },
      { n:7,  name:"Lucas Paquetá",      pos:"CM", club:"West Ham",           caps:58, age:27 },
      { n:8,  name:"Bruno Guimarães",    pos:"CM", club:"Newcastle",          caps:42, age:27 },
      { n:9,  name:"Richarlison",        pos:"ST", club:"Tottenham",          caps:68, age:27 },
      { n:10, name:"Neymar Jr.",         pos:"AM", club:"Al-Hilal",           caps:122, age:33 },
      { n:11, name:"Vinicius Jr.",        pos:"LM", club:"Real Madrid",        caps:55, age:24 },
      { n:13, name:"Éder Militão",       pos:"CB", club:"Real Madrid",        caps:45, age:26 },
      { n:14, name:"Endrick",            pos:"ST", club:"Real Madrid",        caps:18, age:18 },
      { n:15, name:"Éder Militão",       pos:"CB", club:"Real Madrid",        caps:45, age:26 },
      { n:16, name:"Renan Lodi",         pos:"LB", club:"Nottingham Forest",  caps:22, age:26 },
      { n:17, name:"Rodrygo",            pos:"RM", club:"Real Madrid",        caps:42, age:23 },
      { n:18, name:"Gabriel Martinelli", pos:"LM", club:"Arsenal",            caps:35, age:23 },
      { n:19, name:"Gabriel Jesus",      pos:"CF", club:"Arsenal",            caps:68, age:27 },
      { n:20, name:"Gerson",             pos:"CM", club:"Flamengo",           caps:28, age:27 },
      { n:21, name:"Antony",             pos:"RM", club:"Real Betis",         caps:30, age:24 },
      { n:22, name:"Pedro",              pos:"ST", club:"Flamengo",           caps:22, age:27 },
    ],
  },

  GER: {
    coach: "Julian Nagelsmann",
    players: [
      { n:1,  name:"Manuel Neuer",       pos:"GK", club:"Bayern München",     caps:120, age:39 },
      { n:12, name:"Marc-André ter Stegen", pos:"GK", club:"FC Barcelona",    caps:45, age:33 },
      { n:23, name:"Oliver Baumann",     pos:"GK", club:"Hoffenheim",         caps:12, age:34 },
      { n:2,  name:"Joshua Kimmich",     pos:"RB", club:"Bayern München",     caps:95, age:29 },
      { n:3,  name:"David Raum",         pos:"LB", club:"RB Leipzig",         caps:30, age:26 },
      { n:4,  name:"Jonathan Tah",       pos:"CB", club:"Bayer Leverkusen",   caps:38, age:28 },
      { n:5,  name:"Pascal Groß",        pos:"CM", club:"Dortmund",           caps:25, age:33 },
      { n:6,  name:"Anton Schlotterbeck",pos:"CB", club:"Dortmund",           caps:22, age:25 },
      { n:7,  name:"Kai Havertz",        pos:"AM", club:"Arsenal",            caps:58, age:26 },
      { n:8,  name:"Toni Kroos",         pos:"CM", club:"Real Madrid",        caps:110, age:35 },
      { n:9,  name:"Niclas Füllkrug",    pos:"ST", club:"West Ham",           caps:30, age:32 },
      { n:10, name:"Florian Wirtz",      pos:"AM", club:"Bayer Leverkusen",   caps:28, age:21 },
      { n:11, name:"Leroy Sané",         pos:"RM", club:"Bayern München",     caps:62, age:28 },
      { n:13, name:"Thomas Müller",      pos:"AM", club:"Bayern München",     caps:131, age:35 },
      { n:14, name:"Jamal Musiala",      pos:"AM", club:"Bayern München",     caps:42, age:21 },
      { n:15, name:"Nico Schlotterbeck", pos:"CB", club:"Dortmund",           caps:18, age:25 },
      { n:16, name:"Christopher Nkunku", pos:"CF", club:"Chelsea",            caps:18, age:27 },
      { n:17, name:"Deniz Undav",        pos:"ST", club:"Stuttgart",          caps:15, age:28 },
      { n:18, name:"Leon Goretzka",      pos:"CM", club:"Bayern München",     caps:55, age:30 },
      { n:19, name:"Serge Gnabry",       pos:"LM", club:"Bayern München",     caps:48, age:29 },
      { n:20, name:"Jonas Hofmann",      pos:"RM", club:"Bayer Leverkusen",   caps:30, age:32 },
      { n:21, name:"Robert Andrich",     pos:"DM", club:"Bayer Leverkusen",   caps:18, age:30 },
      { n:22, name:"Aleksandar Pavlović",pos:"DM", club:"Bayern München",     caps:10, age:20 },
    ],
  },

  // ── GRUPO F ──────────────────────────────────────────────────

  FRA: {
    coach: "Didier Deschamps",
    players: [
      { n:1,  name:"Mike Maignan",       pos:"GK", club:"AC Milan",           caps:28, age:29 },
      { n:16, name:"Alphonse Aréola",    pos:"GK", club:"West Ham",           caps:8,  age:31 },
      { n:23, name:"Guillaume Restes",   pos:"GK", club:"Toulouse",           caps:3,  age:20 },
      { n:2,  name:"Benjamin Pavard",    pos:"RB", club:"Inter Milan",        caps:60, age:28 },
      { n:3,  name:"Lucas Hernández",    pos:"LB", club:"PSG",                caps:58, age:28 },
      { n:4,  name:"Raphaël Varane",     pos:"CB", club:"Como",               caps:93, age:31 },
      { n:5,  name:"Jules Koundé",       pos:"CB", club:"FC Barcelona",       caps:42, age:26 },
      { n:6,  name:"Adrien Rabiot",      pos:"CM", club:"OM Marseille",       caps:50, age:29 },
      { n:7,  name:"Antoine Griezmann",  pos:"AM", club:"Atletico Madrid",    caps:135, age:33 },
      { n:8,  name:"Aurélien Tchouaméni",pos:"DM", club:"Real Madrid",        caps:38, age:24 },
      { n:9,  name:"Olivier Giroud",     pos:"ST", club:"LAFC",               caps:130, age:38 },
      { n:10, name:"Kylian Mbappé",      pos:"ST", club:"Real Madrid",        caps:82, age:26 },
      { n:11, name:"Ousmane Dembélé",    pos:"RM", club:"PSG",                caps:52, age:27 },
      { n:12, name:"Theo Hernández",     pos:"LB", club:"AC Milan",           caps:28, age:27 },
      { n:13, name:"N'Golo Kanté",       pos:"DM", club:"Al-Ittihad",         caps:55, age:33 },
      { n:14, name:"Dayot Upamecano",    pos:"CB", club:"Bayern München",     caps:32, age:26 },
      { n:15, name:"Randal Kolo Muani",  pos:"CF", club:"Juventus",           caps:28, age:26 },
      { n:17, name:"Matteo Guendouzi",   pos:"CM", club:"OM Marseille",       caps:22, age:26 },
      { n:18, name:"Khéphren Thuram",    pos:"CM", club:"Juventus",           caps:12, age:23 },
      { n:19, name:"Youssouf Fofana",    pos:"CM", club:"AC Milan",           caps:22, age:25 },
      { n:20, name:"Marcus Thuram",      pos:"CF", club:"Inter Milan",        caps:30, age:27 },
      { n:21, name:"Ibrahima Konaté",    pos:"CB", club:"Liverpool",          caps:22, age:25 },
      { n:22, name:"William Saliba",     pos:"CB", club:"Arsenal",            caps:20, age:23 },
    ],
  },

  // ── GRUPO G ──────────────────────────────────────────────────

  ENG: {
    coach: "Thomas Tuchel",
    players: [
      { n:1,  name:"Jordan Pickford",    pos:"GK", club:"Everton",            caps:70, age:30 },
      { n:13, name:"Aaron Ramsdale",     pos:"GK", club:"Southampton",        caps:12, age:26 },
      { n:23, name:"Dean Henderson",     pos:"GK", club:"Crystal Palace",     caps:8,  age:27 },
      { n:2,  name:"Kyle Walker",        pos:"RB", club:"Man City",           caps:82, age:35 },
      { n:3,  name:"Luke Shaw",          pos:"LB", club:"Man Utd",            caps:40, age:29 },
      { n:4,  name:"Declan Rice",        pos:"DM", club:"Arsenal",            caps:52, age:26 },
      { n:5,  name:"John Stones",        pos:"CB", club:"Man City",           caps:72, age:31 },
      { n:6,  name:"Harry Maguire",      pos:"CB", club:"Man Utd",            caps:60, age:31 },
      { n:7,  name:"Bukayo Saka",        pos:"RM", club:"Arsenal",            caps:52, age:22 },
      { n:8,  name:"Jordan Henderson",   pos:"CM", club:"Ajax",               caps:82, age:34 },
      { n:9,  name:"Harry Kane",         pos:"ST", club:"Bayern München",     caps:95, age:31 },
      { n:10, name:"Jude Bellingham",    pos:"AM", club:"Real Madrid",        caps:42, age:21 },
      { n:11, name:"Marcus Rashford",    pos:"LM", club:"Man Utd",            caps:58, age:27 },
      { n:12, name:"Kieran Trippier",    pos:"RB", club:"Newcastle",          caps:50, age:34 },
      { n:14, name:"Conor Gallagher",    pos:"CM", club:"Atletico Madrid",    caps:22, age:24 },
      { n:15, name:"Eric Dier",          pos:"CB", club:"Bayern München",     caps:52, age:30 },
      { n:16, name:"Phil Foden",         pos:"AM", club:"Man City",           caps:42, age:24 },
      { n:17, name:"Ivan Toney",         pos:"ST", club:"Al-Ahli",            caps:10, age:28 },
      { n:18, name:"Jarrod Bowen",       pos:"RM", club:"West Ham",           caps:20, age:27 },
      { n:19, name:"Ollie Watkins",      pos:"ST", club:"Aston Villa",        caps:28, age:29 },
      { n:20, name:"Cole Palmer",        pos:"AM", club:"Chelsea",            caps:18, age:22 },
      { n:21, name:"Ezri Konsa",         pos:"CB", club:"Aston Villa",        caps:12, age:27 },
      { n:22, name:"Levi Colwill",       pos:"CB", club:"Chelsea",            caps:8,  age:21 },
    ],
  },

  COL: {
    coach: "Néstor Lorenzo",
    players: [
      { n:1,  name:"Camilo Vargas",      pos:"GK", club:"Atlas",              caps:40, age:33 },
      { n:12, name:"Álvaro Montero",     pos:"GK", club:"River Plate",        caps:15, age:28 },
      { n:23, name:"David Ospina",       pos:"GK", club:"Millonarios",        caps:125, age:36 },
      { n:2,  name:"Daniel Muñoz",       pos:"RB", club:"Crystal Palace",     caps:32, age:28 },
      { n:3,  name:"Johan Mojica",       pos:"LB", club:"Rayo Vallecano",     caps:45, age:32 },
      { n:4,  name:"Wilmar Barrios",     pos:"DM", club:"Zenit",              caps:65, age:31 },
      { n:5,  name:"Carlos Cuesta",      pos:"CB", club:"Genk",               caps:25, age:26 },
      { n:6,  name:"Jhon Lucumí",        pos:"CB", club:"Bologna",            caps:22, age:26 },
      { n:7,  name:"James Rodríguez",    pos:"AM", club:"Rayo Vallecano",     caps:98, age:33 },
      { n:8,  name:"Mateus Uribe",       pos:"CM", club:"Porto",              caps:52, age:32 },
      { n:9,  name:"Falcao",             pos:"ST", club:"Millonarios",        caps:109, age:39 },
      { n:10, name:"Jhon Arias",         pos:"AM", club:"Fluminense",         caps:38, age:27 },
      { n:11, name:"Luis Díaz",          pos:"LM", club:"Liverpool",          caps:48, age:27 },
      { n:13, name:"Davinson Sánchez",   pos:"CB", club:"Galatasaray",        caps:72, age:28 },
      { n:14, name:"Richard Ríos",       pos:"CM", club:"Palmeiras",          caps:22, age:24 },
      { n:15, name:"Yerry Mina",         pos:"CB", club:"Fiorentina",         caps:55, age:30 },
      { n:16, name:"Juan Cuadrado",      pos:"RM", club:"Inter Miami",        caps:120, age:36 },
      { n:17, name:"Rafael Santos Borré",pos:"ST", club:"Eintracht Frankfurt",caps:45, age:28 },
      { n:18, name:"Jhon Córdoba",       pos:"ST", club:"Krasnodar",          caps:32, age:31 },
      { n:19, name:"Duvan Zapata",       pos:"ST", club:"Torino",             caps:68, age:33 },
      { n:20, name:"Juan Fernando Quintero", pos:"AM", club:"Junior",         caps:45, age:31 },
      { n:21, name:"Luis Sinisterra",    pos:"LM", club:"Bournemouth",        caps:30, age:25 },
      { n:22, name:"Jorge Carrascal",    pos:"AM", club:"Zenit",              caps:28, age:25 },
    ],
  },

  // ── GRUPO H ──────────────────────────────────────────────────

  POR: {
    coach: "Roberto Martínez",
    players: [
      { n:1,  name:"Rui Patrício",       pos:"GK", club:"Roma",               caps:110, age:36 },
      { n:12, name:"Diogo Costa",        pos:"GK", club:"Porto",              caps:22, age:25 },
      { n:23, name:"José Sá",            pos:"GK", club:"Wolves",             caps:12, age:31 },
      { n:2,  name:"João Cancelo",       pos:"RB", club:"Al-Hilal",           caps:68, age:30 },
      { n:3,  name:"Nuno Mendes",        pos:"LB", club:"PSG",                caps:32, age:22 },
      { n:4,  name:"Rúben Dias",         pos:"CB", club:"Man City",           caps:62, age:27 },
      { n:5,  name:"Raphaël Guerreiro",  pos:"LB", club:"Bayern München",     caps:70, age:31 },
      { n:6,  name:"João Palinha",       pos:"DM", club:"Al-Qadsiah",         caps:32, age:29 },
      { n:7,  name:"Cristiano Ronaldo",  pos:"ST", club:"Al-Nassr",           caps:213, age:41 },
      { n:8,  name:"João Moutinho",      pos:"CM", club:"Vitória SC",         caps:148, age:38 },
      { n:9,  name:"André Silva",        pos:"ST", club:"RB Leipzig",         caps:58, age:29 },
      { n:10, name:"Bernardo Silva",     pos:"AM", club:"Man City",           caps:78, age:30 },
      { n:11, name:"Diogo Jota",         pos:"LM", club:"Liverpool",          caps:48, age:28 },
      { n:13, name:"Danilo Pereira",     pos:"CB", club:"PSG",                caps:55, age:33 },
      { n:14, name:"William Carvalho",   pos:"DM", club:"Real Betis",         caps:78, age:32 },
      { n:15, name:"José Fonte",         pos:"CB", club:"LOSC Lille",         caps:72, age:40 },
      { n:16, name:"Vitinha",            pos:"CM", club:"PSG",                caps:28, age:24 },
      { n:17, name:"Rafael Leão",        pos:"LM", club:"AC Milan",           caps:38, age:25 },
      { n:18, name:"Rúben Neves",        pos:"CM", club:"Al-Hilal",           caps:60, age:27 },
      { n:19, name:"Pedro Neto",         pos:"RM", club:"Chelsea",            caps:28, age:24 },
      { n:20, name:"Francisco Conceição",pos:"RM", club:"Juventus",           caps:15, age:22 },
      { n:21, name:"Otávio",             pos:"CM", club:"Al-Nassr",           caps:38, age:29 },
      { n:22, name:"Pepe",               pos:"CB", club:"Porto",              caps:140, age:43 },
    ],
  },

  EGY: {
    coach: "Hossam Hassan",
    players: [
      { n:1,  name:"Mohamed El-Shenawy", pos:"GK", club:"Al Ahly",            caps:45, age:36 },
      { n:12, name:"Ahmed El-Shenawy",   pos:"GK", club:"Zamalek",            caps:18, age:30 },
      { n:23, name:"Ibrahim Adel",       pos:"GK", club:"Al Ahly",            caps:5,  age:24 },
      { n:2,  name:"Ahmed Hegazi",       pos:"CB", club:"Al-Ittihad",         caps:80, age:33 },
      { n:3,  name:"Omar Kamal",         pos:"LB", club:"Al Ahly",            caps:15, age:22 },
      { n:4,  name:"Tarek Hamed",        pos:"DM", club:"Al-Ain",             caps:55, age:32 },
      { n:5,  name:"Mohamed Abdel-Moneim", pos:"CB", club:"Zamalek",          caps:28, age:28 },
      { n:6,  name:"Mahmoud Hamdi",      pos:"CB", club:"Al Ahly",            caps:22, age:27 },
      { n:7,  name:"Ramadan Sobhi",      pos:"AM", club:"Al Ahly",            caps:52, age:27 },
      { n:8,  name:"Mohamed Ibrahim",    pos:"CM", club:"Nottingham Forest",  caps:18, age:22 },
      { n:9,  name:"Marwan Hamdy",       pos:"ST", club:"Pyramids FC",        caps:30, age:25 },
      { n:10, name:"Mohamed Salah",      pos:"RM", club:"Liverpool",          caps:95, age:33 },
      { n:11, name:"Mostafa Mohamed",    pos:"ST", club:"Galatasaray",        caps:38, age:25 },
      { n:13, name:"Ahmed Fatouh",       pos:"LB", club:"Al Ahly",            caps:20, age:26 },
      { n:14, name:"Amr El-Sulaya",      pos:"CM", club:"Al Ahly",            caps:12, age:25 },
      { n:15, name:"Mohamed Hany",       pos:"RB", club:"Fortuna Düsseldorf", caps:22, age:24 },
      { n:16, name:"Trézéguet",          pos:"AM", club:"Istanbul Başakşehir", caps:55, age:30 },
      { n:17, name:"Mahmoud Hamada",     pos:"CM", club:"Pyramids FC",        caps:15, age:25 },
      { n:18, name:"Omar Marmoush",      pos:"CF", club:"Man City",           caps:28, age:26 },
      { n:19, name:"Mahmoud Hassan",     pos:"LM", club:"Al Ahly",            caps:35, age:28 },
      { n:20, name:"Akram Tawfik",       pos:"RM", club:"Pyramids FC",        caps:10, age:23 },
      { n:21, name:"Amr Warda",          pos:"RM", club:"PAOK",               caps:45, age:30 },
      { n:22, name:"Zizo",               pos:"AM", club:"Al Ahly",            caps:20, age:28 },
    ],
  },

  // ── GRUPO I ──────────────────────────────────────────────────

  NED: {
    coach: "Ronald Koeman",
    players: [
      { n:1,  name:"Bart Verbruggen",    pos:"GK", club:"Brighton",           caps:10, age:22 },
      { n:13, name:"Mark Flekken",       pos:"GK", club:"Brentford",          caps:8,  age:31 },
      { n:23, name:"Remko Pasveer",      pos:"GK", club:"Ajax",               caps:12, age:40 },
      { n:2,  name:"Denzel Dumfries",    pos:"RB", club:"Inter Milan",        caps:55, age:28 },
      { n:3,  name:"Daley Blind",        pos:"LB", club:"Girona",             caps:110, age:34 },
      { n:4,  name:"Virgil van Dijk",    pos:"CB", club:"Liverpool",          caps:68, age:33 },
      { n:5,  name:"Nathan Aké",         pos:"CB", club:"Man City",           caps:42, age:30 },
      { n:6,  name:"Frenkie de Jong",    pos:"CM", club:"FC Barcelona",       caps:55, age:27 },
      { n:7,  name:"Steven Bergwijn",    pos:"RM", club:"Ajax",               caps:48, age:26 },
      { n:8,  name:"Teun Koopmeiners",   pos:"CM", club:"Juventus",           caps:28, age:26 },
      { n:9,  name:"Wout Weghorst",      pos:"ST", club:"Burnley",            caps:42, age:32 },
      { n:10, name:"Memphis Depay",      pos:"CF", club:"Corinthians",        caps:98, age:30 },
      { n:11, name:"Donyell Malen",      pos:"LM", club:"Dortmund",           caps:35, age:25 },
      { n:12, name:"Jurriën Timber",     pos:"RB", club:"Arsenal",            caps:25, age:23 },
      { n:14, name:"Marten de Roon",     pos:"DM", club:"Atalanta",           caps:48, age:33 },
      { n:15, name:"Stefan de Vrij",     pos:"CB", club:"Inter Milan",        caps:62, age:32 },
      { n:16, name:"Tijjani Reijnders",  pos:"CM", club:"AC Milan",           caps:22, age:26 },
      { n:17, name:"Noa Lang",           pos:"LM", club:"PSV Eindhoven",      caps:18, age:25 },
      { n:18, name:"Xavi Simons",        pos:"AM", club:"RB Leipzig",         caps:20, age:22 },
      { n:19, name:"Myron Boadu",        pos:"ST", club:"AS Monaco",          caps:12, age:23 },
      { n:20, name:"Cody Gakpo",         pos:"LM", club:"Liverpool",          caps:38, age:25 },
      { n:21, name:"Ryan Gravenberch",   pos:"CM", club:"Liverpool",          caps:18, age:22 },
      { n:22, name:"Lutsharel Geertruida",pos:"RB", club:"RB Leipzig",        caps:15, age:24 },
    ],
  },

  SEN: {
    coach: "Aliou Cissé",
    players: [
      { n:1,  name:"Édouard Mendy",      pos:"GK", club:"Al-Ahli",            caps:38, age:32 },
      { n:16, name:"Alfred Gomis",       pos:"GK", club:"Rennes",             caps:22, age:31 },
      { n:23, name:"Seny Dieng",         pos:"GK", club:"Middlesbrough",      caps:12, age:29 },
      { n:2,  name:"Youssouf Sabaly",    pos:"RB", club:"Real Betis",         caps:42, age:32 },
      { n:3,  name:"Fodé Ballo-Touré",   pos:"LB", club:"Fulham",             caps:28, age:27 },
      { n:4,  name:"Kalidou Koulibaly",  pos:"CB", club:"Al-Hilal",           caps:72, age:33 },
      { n:5,  name:"Abdou Diallo",       pos:"CB", club:"RB Leipzig",         caps:35, age:28 },
      { n:6,  name:"Cheikhou Kouyaté",   pos:"DM", club:"Nottingham Forest",  caps:85, age:35 },
      { n:7,  name:"Sadio Mané",         pos:"LM", club:"Al-Nassr",           caps:98, age:32 },
      { n:8,  name:"Idrissa Gueye",      pos:"CM", club:"Everton",            caps:80, age:35 },
      { n:9,  name:"Boulaye Dia",        pos:"ST", club:"Lazio",              caps:30, age:27 },
      { n:10, name:"Ismaïla Sarr",       pos:"RM", club:"Crystal Palace",     caps:52, age:26 },
      { n:11, name:"Famara Diedhiou",    pos:"ST", club:"Al-Fayha",           caps:40, age:32 },
      { n:12, name:"Saliou Ciss",        pos:"LB", club:"Valenciennes",       caps:38, age:36 },
      { n:13, name:"Salif Sané",         pos:"CB", club:"Schalke",            caps:32, age:33 },
      { n:14, name:"Nicolas Jackson",    pos:"ST", club:"Chelsea",            caps:18, age:23 },
      { n:15, name:"Pape Matar Sarr",    pos:"CM", club:"Tottenham",          caps:22, age:22 },
      { n:17, name:"Krepin Diatta",      pos:"RM", club:"AS Monaco",          caps:38, age:25 },
      { n:18, name:"Moussa Niakhaté",    pos:"CB", club:"Nottingham Forest",  caps:18, age:28 },
      { n:19, name:"Iliman Ndiaye",      pos:"AM", club:"Everton",            caps:22, age:24 },
      { n:20, name:"Nampalys Mendy",     pos:"DM", club:"Nice",               caps:35, age:32 },
      { n:21, name:"Lamine Camara",      pos:"CM", club:"AS Monaco",          caps:12, age:21 },
      { n:22, name:"Formose Mendy",      pos:"LB", club:"Almería",            caps:10, age:26 },
    ],
  },

  // ── GRUPO J ──────────────────────────────────────────────────

  CRO: {
    coach: "Zlatko Dalić",
    players: [
      { n:1,  name:"Dominik Livaković",  pos:"GK", club:"Fenerbahce",         caps:52, age:29 },
      { n:12, name:"Ivica Ivušić",       pos:"GK", club:"Osijek",             caps:12, age:30 },
      { n:23, name:"Lovre Kalinić",      pos:"GK", club:"Hajduk Split",       caps:22, age:34 },
      { n:2,  name:"Josip Stanišić",     pos:"RB", club:"Bayer Leverkusen",   caps:18, age:24 },
      { n:3,  name:"Borna Sosa",         pos:"LB", club:"Ajax",               caps:30, age:26 },
      { n:4,  name:"Ivan Perišić",       pos:"LM", club:"Hajduk Split",       caps:122, age:35 },
      { n:5,  name:"Duje Ćaleta-Car",    pos:"CB", club:"Southampton",        caps:30, age:27 },
      { n:6,  name:"Ante Budimir",       pos:"ST", club:"Osasuna",            caps:22, age:32 },
      { n:7,  name:"Ivan Rakitić",       pos:"CM", club:"Hajduk Split",       caps:118, age:36 },
      { n:8,  name:"Mateo Kovačić",      pos:"CM", club:"Man City",           caps:80, age:30 },
      { n:9,  name:"Andrej Kramarić",    pos:"CF", club:"Hoffenheim",         caps:72, age:33 },
      { n:10, name:"Luka Modrić",        pos:"CM", club:"Real Madrid",        caps:175, age:40 },
      { n:11, name:"Nikola Vlašić",      pos:"AM", club:"Torino",             caps:55, age:27 },
      { n:13, name:"Domagoj Vida",       pos:"CB", club:"AEK Athens",         caps:98, age:35 },
      { n:14, name:"Luka Sučić",         pos:"AM", club:"RB Salzburg",        caps:22, age:22 },
      { n:15, name:"Joško Gvardiol",     pos:"CB", club:"Man City",           caps:40, age:22 },
      { n:16, name:"Lovro Majer",        pos:"AM", club:"Wolfsburg",          caps:38, age:26 },
      { n:17, name:"Marko Livaja",       pos:"ST", club:"Hajduk Split",       caps:30, age:30 },
      { n:18, name:"Mislav Oršić",       pos:"LM", club:"Celta Vigo",         caps:40, age:32 },
      { n:19, name:"Bruno Petković",     pos:"ST", club:"Dinamo Zagreb",      caps:35, age:30 },
      { n:20, name:"Martin Erlić",       pos:"CB", club:"Bologna",            caps:18, age:26 },
      { n:21, name:"Marko Pjaca",        pos:"RM", club:"Hajduk Split",       caps:30, age:29 },
      { n:22, name:"Borna Barišić",      pos:"LB", club:"Rangers",            caps:40, age:31 },
    ],
  },

  SRB: {
    coach: "Dragan Stojković",
    players: [
      { n:1,  name:"Vanja Milinković-Savić", pos:"GK", club:"Torino",        caps:22, age:27 },
      { n:12, name:"Predrag Rajković",   pos:"GK", club:"OM Marseille",       caps:35, age:30 },
      { n:23, name:"Đorđe Petrović",     pos:"GK", club:"Chelsea",            caps:8,  age:24 },
      { n:2,  name:"Strahinja Pavlović", pos:"CB", club:"AC Milan",           caps:22, age:23 },
      { n:3,  name:"Miloš Veljković",    pos:"CB", club:"Werder Bremen",      caps:35, age:29 },
      { n:4,  name:"Nemanja Maksimović", pos:"DM", club:"Getafe",             caps:38, age:32 },
      { n:5,  name:"Nikola Milenković",  pos:"CB", club:"Nottingham Forest",  caps:52, age:27 },
      { n:6,  name:"Nemanja Matić",      pos:"DM", club:"Lyon",               caps:65, age:36 },
      { n:7,  name:"Filip Kostić",       pos:"LM", club:"Juventus",           caps:60, age:32 },
      { n:8,  name:"Sergej Milinković-Savić", pos:"CM", club:"Al-Hilal",     caps:65, age:29 },
      { n:9,  name:"Aleksandar Mitrović",pos:"ST", club:"Al-Hilal",           caps:80, age:30 },
      { n:10, name:"Dušan Tadić",        pos:"AM", club:"Fenerbahce",         caps:80, age:36 },
      { n:11, name:"Dušan Vlahović",     pos:"ST", club:"Juventus",           caps:42, age:24 },
      { n:13, name:"Uroš Spajić",        pos:"CB", club:"Anderlecht",         caps:18, age:26 },
      { n:14, name:"Ivan Ilić",          pos:"CM", club:"Torino",             caps:25, age:23 },
      { n:15, name:"Andrija Živković",   pos:"RM", club:"PAOK",               caps:38, age:28 },
      { n:16, name:"Darko Lazović",      pos:"LM", club:"Hellas Verona",      caps:38, age:34 },
      { n:17, name:"Luka Jović",         pos:"ST", club:"AC Milan",           caps:38, age:27 },
      { n:18, name:"Nemanja Gudelj",     pos:"DM", club:"Sevilla",            caps:30, age:33 },
      { n:19, name:"Sasa Lukić",         pos:"CM", club:"Fulham",             caps:28, age:27 },
      { n:20, name:"Filip Đuričić",      pos:"AM", club:"Anderlecht",         caps:40, age:32 },
      { n:21, name:"Petar Ratkov",       pos:"ST", club:"Salzburg",           caps:10, age:22 },
      { n:22, name:"Raša Đukić",         pos:"RB", club:"LOSC Lille",         caps:5,  age:21 },
    ],
  },

  // ── GRUPO L ──────────────────────────────────────────────────

  DEN: {
    coach: "Brian Riemer",
    players: [
      { n:1,  name:"Kasper Schmeichel",  pos:"GK", club:"Anderlecht",         caps:100, age:38 },
      { n:13, name:"Mathias Jensen",     pos:"GK", club:"Brentford",          caps:8,  age:28 },
      { n:23, name:"Oliver Christensen", pos:"GK", club:"Fiorentina",         caps:8,  age:24 },
      { n:2,  name:"Henrik Dalsgaard",   pos:"RB", club:"Brentford",          caps:50, age:35 },
      { n:3,  name:"Joakim Mæhle",       pos:"LB", club:"Atalanta",           caps:50, age:28 },
      { n:4,  name:"Simon Kjær",         pos:"CB", club:"AC Milan",           caps:120, age:35 },
      { n:5,  name:"Andreas Christensen",pos:"CB", club:"FC Barcelona",       caps:45, age:28 },
      { n:6,  name:"Thomas Delaney",     pos:"DM", club:"Anderlecht",         caps:72, age:33 },
      { n:7,  name:"Jesper Lindstrøm",   pos:"AM", club:"Everton",            caps:22, age:24 },
      { n:8,  name:"Christian Eriksen",  pos:"AM", club:"Man Utd",            caps:115, age:32 },
      { n:9,  name:"Rasmus Højlund",     pos:"ST", club:"Man Utd",            caps:25, age:22 },
      { n:10, name:"Christian Nørgaard", pos:"DM", club:"Brentford",          caps:35, age:30 },
      { n:11, name:"Kasper Dolberg",     pos:"ST", club:"Eintracht Frankfurt", caps:38, age:27 },
      { n:12, name:"Victor Nelsson",     pos:"CB", club:"Galatasaray",        caps:25, age:25 },
      { n:14, name:"Mathias Jørgensen", pos:"CB", club:"Brentford",          caps:22, age:33 },
      { n:15, name:"Pierre-Emile Højbjerg", pos:"CM", club:"OM Marseille",   caps:72, age:29 },
      { n:16, name:"Jonas Wind",         pos:"ST", club:"Wolfsburg",          caps:25, age:25 },
      { n:17, name:"Yussuf Poulsen",     pos:"ST", club:"RB Leipzig",         caps:72, age:30 },
      { n:18, name:"Jacob Bruun Larsen", pos:"LM", club:"Hamilton Academical",caps:22, age:26 },
      { n:19, name:"Mikkel Damsgaard",   pos:"AM", club:"Brentford",          caps:32, age:24 },
      { n:20, name:"Viktor Gyökeres",    pos:"ST", club:"Sporting CP",        caps:22, age:26 },
      { n:21, name:"Mads Hermansen",     pos:"GK", club:"Leicester City",     caps:5,  age:24 },
      { n:22, name:"Mathias Kvistgaarden",pos:"LM", club:"Brentford",        caps:8,  age:22 },
    ],
  },

  AUT: {
    coach: "Ralf Rangnick",
    players: [
      { n:1,  name:"Patrick Pentz",      pos:"GK", club:"Bayer Leverkusen",   caps:22, age:27 },
      { n:12, name:"Alexander Schlager", pos:"GK", club:"Augsburg",           caps:18, age:30 },
      { n:23, name:"Heinz Lindner",      pos:"GK", club:"Eintracht Frankfurt", caps:35, age:35 },
      { n:2,  name:"Stefan Lainer",      pos:"RB", club:"Gladbach",           caps:62, age:32 },
      { n:3,  name:"Phillip Mwene",      pos:"LB", club:"PSV Eindhoven",      caps:28, age:30 },
      { n:4,  name:"Florian Grillitsch", pos:"DM", club:"Hoffenheim",         caps:45, age:29 },
      { n:5,  name:"Martin Hinteregger", pos:"CB", club:"Eintracht Frankfurt", caps:72, age:32 },
      { n:6,  name:"Aleksandar Dragović",pos:"CB", club:"Bayer Leverkusen",   caps:85, age:34 },
      { n:7,  name:"Marko Arnautović",   pos:"ST", club:"Inter Milan",        caps:110, age:37 },
      { n:8,  name:"David Alaba",        pos:"CB", club:"Real Madrid",        caps:110, age:32 },
      { n:9,  name:"Andreas Weimann",    pos:"ST", club:"Bristol City",       caps:35, age:32 },
      { n:10, name:"Marcel Sabitzer",    pos:"CM", club:"Man Utd",            caps:65, age:30 },
      { n:11, name:"Christoph Baumgartner", pos:"AM", club:"RB Leipzig",      caps:38, age:25 },
      { n:13, name:"Gernot Trauner",     pos:"CB", club:"Feyenoord",          caps:40, age:32 },
      { n:14, name:"Konrad Laimer",      pos:"CM", club:"Bayern München",     caps:28, age:27 },
      { n:15, name:"Michael Gregoritsch",pos:"ST", club:"Freiburg",           caps:42, age:30 },
      { n:16, name:"Xaver Schlager",     pos:"CM", club:"RB Leipzig",         caps:38, age:27 },
      { n:17, name:"Romano Schmid",      pos:"AM", club:"Werder Bremen",      caps:18, age:25 },
      { n:18, name:"Kevin Danso",        pos:"CB", club:"RC Lens",            caps:25, age:25 },
      { n:19, name:"Patrick Wimmer",     pos:"LM", club:"Wolfsburg",          caps:22, age:23 },
      { n:20, name:"Nicolas Seiwald",    pos:"DM", club:"RB Leipzig",         caps:20, age:23 },
      { n:21, name:"Thierry Correia",    pos:"RB", club:"Valencia",           caps:12, age:25 },
      { n:22, name:"Thomas Goiginger",   pos:"RM", club:"LASK",               caps:12, age:30 },
    ],
  },

  HUN: {
    coach: "Marco Rossi",
    players: [
      { n:1,  name:"Péter Gulácsi",      pos:"GK", club:"RB Leipzig",         caps:72, age:34 },
      { n:12, name:"Ádám Bogdán",        pos:"GK", club:"Ferencváros",        caps:28, age:37 },
      { n:23, name:"Dávid Hancko",       pos:"GK", club:"Debrecen",           caps:8,  age:25 },
      { n:2,  name:"Ádám Fiola",         pos:"RB", club:"Fehérvár",           caps:42, age:33 },
      { n:3,  name:"Zsolt Kalmár",       pos:"CM", club:"Ferencváros",        caps:38, age:29 },
      { n:4,  name:"Willi Orbán",        pos:"CB", club:"RB Leipzig",         caps:50, age:31 },
      { n:5,  name:"Attila Szalai",      pos:"CB", club:"Hoffenheim",         caps:45, age:26 },
      { n:6,  name:"Ádám Nagy",          pos:"DM", club:"Bristol City",       caps:65, age:31 },
      { n:7,  name:"Roland Sallai",      pos:"RM", club:"Freiburg",           caps:42, age:26 },
      { n:8,  name:"Ádám Hanga",         pos:"CM", club:"Barcelona (BSK)",    caps:20, age:35 },
      { n:9,  name:"Ádám Martin",        pos:"ST", club:"Venezia",            caps:28, age:27 },
      { n:10, name:"Dominik Szoboszlai", pos:"CM", club:"Liverpool",          caps:52, age:24 },
      { n:11, name:"Roland Varga",       pos:"LM", club:"Ferencváros",        caps:22, age:26 },
      { n:13, name:"Endre Botka",        pos:"CB", club:"Ferencváros",        caps:18, age:28 },
      { n:14, name:"Mihály Kámber",      pos:"CM", club:"Lausanne-Sport",     caps:12, age:22 },
      { n:15, name:"Lőrinc Pintér",      pos:"CB", club:"Lille",              caps:10, age:22 },
      { n:16, name:"Kevin Varga",        pos:"RB", club:"Trabzonspor",        caps:18, age:24 },
      { n:17, name:"László Kleinheisler",pos:"CM", club:"Anderlecht",         caps:42, age:30 },
      { n:18, name:"Dániel Gazdag",      pos:"AM", club:"Philadelphia Union", caps:22, age:28 },
      { n:19, name:"Martin Ádám",        pos:"ST", club:"Barnsley",           caps:18, age:28 },
      { n:20, name:"Loic Nego",          pos:"RB", club:"Le Havre",           caps:30, age:32 },
      { n:21, name:"András Schäfer",     pos:"CM", club:"Union Berlin",       caps:35, age:25 },
      { n:22, name:"Zalán Vancsa",       pos:"LM", club:"RB Leipzig",         caps:12, age:20 },
    ],
  },

  TUN: {
    coach: "Jalel Kadri",
    players: [
      { n:1,  name:"Aymen Dahmen",       pos:"GK", club:"Montpellier",        caps:20, age:28 },
      { n:12, name:"Bechir Ben Saïd",    pos:"GK", club:"Stade Tunisien",     caps:30, age:35 },
      { n:23, name:"Farouk Ben Mustapha",pos:"GK", club:"Qatar SC",           caps:40, age:36 },
      { n:2,  name:"Mohamed Dräger",     pos:"RB", club:"Middlesbrough",      caps:25, age:27 },
      { n:3,  name:"Dylan Bronn",        pos:"CB", club:"Salernitana",        caps:28, age:28 },
      { n:4,  name:"Yassine Meriah",     pos:"CB", club:"Kasımpaşa",          caps:32, age:30 },
      { n:5,  name:"Ali Maaloul",        pos:"LB", club:"Al Ahly",            caps:75, age:34 },
      { n:6,  name:"Ellyes Skhiri",      pos:"DM", club:"Eintracht Frankfurt", caps:48, age:29 },
      { n:7,  name:"Wahbi Khazri",       pos:"AM", club:"Montpellier",        caps:68, age:33 },
      { n:8,  name:"Aïssa Laïdouni",     pos:"CM", club:"Ferencváros",        caps:30, age:27 },
      { n:9,  name:"Seifeddine Jaziri",  pos:"ST", club:"Ankaraspor",         caps:38, age:31 },
      { n:10, name:"Youssef Msakni",     pos:"AM", club:"Al-Arabi",           caps:95, age:34 },
      { n:11, name:"Ferjani Sassi",      pos:"CM", club:"Nagoya Grampus",     caps:78, age:33 },
      { n:13, name:"Montassar Talbi",    pos:"CB", club:"RC Lens",            caps:15, age:24 },
      { n:14, name:"Ghaylane Chaalali",  pos:"CM", club:"Espérance Tunis",    caps:18, age:28 },
      { n:15, name:"Mohamed Ben Romdhane", pos:"AM", club:"Nantes",           caps:12, age:24 },
      { n:16, name:"Hannibal Mejbri",    pos:"CM", club:"Sevilla",            caps:18, age:22 },
      { n:17, name:"Nader Ghaddioui",    pos:"ST", club:"Panathinaikos",      caps:22, age:33 },
      { n:18, name:"Mohamed Ali Ben Romdhane", pos:"RM", club:"Zulte Waregem",caps:10,age:22 },
      { n:19, name:"Saâd Bguir",         pos:"ST", club:"Espérance Tunis",    caps:8,  age:22 },
      { n:20, name:"Naïm Sliti",         pos:"AM", club:"Dijon",              caps:35, age:31 },
      { n:21, name:"Hamza Mathlouthi",   pos:"LB", club:"Kasımpaşa",          caps:18, age:27 },
      { n:22, name:"Mohamed Ounalli",    pos:"RB", club:"Espérance Tunis",    caps:10, age:24 },
    ],
  },

};

// Accessor: obtiene la convocatoria de un equipo por shortName
function getSquad(shortName) {
  return SQUADS[shortName] || null;
}
